columns:
  loan_id: int
  no_of_dependents: int
  education: object
  self_employed: object
  income_annum: float
  loan_amount: float
  loan_term: int
  cibil_score: int
  residential_assets_value: float
  commercial_assets_value: float
  luxury_assets_value: float
  bank_asset_value: float
  loan_status: object


